- hosts: localhost
  vars_files:
    - path_vars.yml
  vars:
    cruise: yes
    zoox: no
  roles:
    - {role: python, tags: [python, vim, ycm]}
    - {role: ansible-role-ripgrep, tags: [ripgrep]}
    - {role: packages, tags: [packages]}
    - {role: tmux, tags: [tmux]}
    - {role: git, tags: [git]}
    - {role: gitflow, tags: [gitflow]}
    - {role: vim, tags: [vim]}
      # ycm requires cmake version 3.14 or higher now.
    - {role: ansible-role-cmake, tags: [cmake, vim, ycm], cmake_version: 3.14}
    - {role: youcompleteme, tags: [vim, ycm], cmake_version: 3.14}
    - {role: dotfiles, tags: [dotfiles]}
