/**
 * Running summaries in the powerbar.
 *
 * - session-summary: a headline for this session, regenerated by a fast model after each
 *   settled run (and mid-run when a run goes long). The full summary is persisted as a
 *   `session-pulse` custom entry, so it survives resume.
 * - workspace-context: what every recent or running pi session in the same workspace is
 *   doing. Each session publishes its summary to ~/.pi/agent/session-pulse/<workspace>/,
 *   and every session reads that directory and synthesizes a workspace digest.
 * - /pulse toggles a multi-line panel with both summaries; /pulse refresh forces a rerun.
 * - The same model call keeps a short session name current (shown by /resume and the workspace
 *   view), unless the user has set one with /name.
 * - Inside tmux, the window is named after the session name of whichever pane is active; the
 *   pane's title is cleared when the session ends.
 *
 * Environment:
 *   PI_PULSE_MODEL         provider/model for summaries (default github-copilot/claude-sonnet-5.5,
 *                          falls back to the session model unless that is a Cursor CLI model)
 *   PI_PULSE_RECENT_HOURS  how far back the workspace view looks (default 24)
 *   PI_PULSE_TMUX_WIDTH    max tmux window name length (default 32; 0 disables renaming)
 */

import { execFile, execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { appendFileSync, mkdirSync, readdirSync, readFileSync, realpathSync, renameSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, relative, resolve, sep } from "node:path";
import type { ExtensionAPI, ExtensionContext, SessionEntry } from "@earendil-works/pi-coding-agent";
import { convertToLlm, serializeConversation } from "@earendil-works/pi-coding-agent";
import { truncateToWidth } from "@earendil-works/pi-tui";

const ENTRY_TYPE = "session-pulse";
const STORE_ROOT = join(homedir(), ".pi", "agent", "session-pulse");
const WORKSPACES_ROOT = process.env.POPPY_WORKSPACES_ROOT ?? join(homedir(), "workspaces");
const MODEL_SPEC = process.env.PI_PULSE_MODEL ?? "github-copilot/claude-sonnet-5.5";
const RECENT_MS = Number(process.env.PI_PULSE_RECENT_HOURS ?? 24) * 3600_000;
const LOG_FILE = join(STORE_ROOT, "errors.log");
const MAX_TRANSCRIPT_CHARS = 60_000;
const MID_RUN_REFRESH_MS = 4 * 60_000;
const WORKSPACE_POLL_MS = 30_000;
const WORKSPACE_DIGEST_MIN_MS = 3 * 60_000;
const TMUX_WIDTH = Number(process.env.PI_PULSE_TMUX_WIDTH ?? 32);
const TMUX_PANE = process.env.TMUX && TMUX_WIDTH > 0 ? process.env.TMUX_PANE : undefined;
// Shared with ~/.copilot/statusline-summary.py.
const TMUX_TITLE_OPTION = "@agent_title";
const TMUX_NAME_FORMAT = `#{?${TMUX_TITLE_OPTION},#{${TMUX_TITLE_OPTION}},#{pane_current_command}}`;

type State = "working" | "idle" | "ended";

interface Pulse {
	headline: string;
	summary: string;
	name?: string;
}

interface SessionRecord extends Pulse {
	sessionId: string;
	sessionFile?: string;
	name?: string;
	cwd: string;
	pid: number;
	state: State;
	updatedAt: number;
}

const SESSION_PROMPT = `You maintain a running status summary of a coding-agent session for a status bar.
Given the previous summary (may be empty) and the conversation transcript, output exactly:

NAME: <2 to 5 words naming the session's overall task, like a tab title; keep the previous name unless the session's focus has clearly changed>
HEADLINE: <at most 70 characters: what the session is doing right now, present tense, no trailing period>
- Goal: <the user's overall objective>
- Done: <key results, decisions, files changed>
- Now: <what is in progress or was just finished>
- Next: <next step, open question, or blocker; "none" if finished>

Be specific (name files, targets, PRs, run IDs). Keep each bullet under 160 characters.
Do not continue the conversation or answer its questions.`;

const WORKSPACE_PROMPT = `You summarize parallel coding-agent sessions running in one workspace (a single git checkout).
Given per-session summaries, output exactly:

HEADLINE: <at most 70 characters: the overall state of work in this workspace>
- <one bullet per theme of work, merging sessions that work on the same thing>
- Conflicts: <sessions likely touching the same files/branch, or "none">

Each bullet under 160 characters. Be concrete.`;

function logError(where: string, error: unknown) {
	try {
		mkdirSync(STORE_ROOT, { recursive: true });
		const detail = error instanceof Error ? (error.stack ?? error.message) : String(error);
		appendFileSync(LOG_FILE, `${new Date().toISOString()} ${where}: ${detail}\n`);
	} catch {}
}

function realpath(path: string): string {
	try {
		return realpathSync(path);
	} catch {
		return resolve(path);
	}
}

function workspaceKey(cwd: string): string {
	const root = realpath(WORKSPACES_ROOT);
	const rel = relative(root, realpath(cwd));
	const workspace = rel.split(sep)[0];
	if (workspace && !rel.startsWith("..") && workspace !== ".poppy") {
		try {
			if (statSync(join(root, workspace)).isDirectory()) return workspace;
		} catch {}
	}
	return realpath(cwd).replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^-+/, "");
}

function pidAlive(pid: number): boolean {
	try {
		process.kill(pid, 0);
		return true;
	} catch (error) {
		return (error as NodeJS.ErrnoException).code === "EPERM";
	}
}

function parsePulse(text: string): Pulse | undefined {
	const headlineField = /^\s*\**HEADLINE:?\**\s*/i;
	const nameField = /^\s*\**NAME\**:\**\s*/i;
	const lines = text.trim().split("\n");
	const index = lines.findIndex((line) => headlineField.test(line));
	if (index < 0) return undefined;
	const headline = lines[index].replace(headlineField, "").trim().replace(/\.$/, "");
	const nameLine = lines.find((line) => nameField.test(line));
	const name = (nameLine ?? "")
		.replace(nameField, "")
		.trim()
		.replace(/^["'`]+|["'`.]+$/g, "");
	const summary = lines
		.slice(index + 1)
		.filter((line) => line.trim() && !nameField.test(line))
		.join("\n");
	return headline ? { headline, summary, ...(name ? { name } : {}) } : undefined;
}

function clip(text: string, width: number): string {
	const chars = Array.from(text);
	return chars.length <= width ? text : `${chars.slice(0, width - 1).join("").trimEnd()}…`;
}

function age(ms: number): string {
	const minutes = Math.round(ms / 60_000);
	if (minutes < 1) return "now";
	if (minutes < 60) return `${minutes}m`;
	const hours = Math.round(minutes / 60);
	return hours < 48 ? `${hours}h` : `${Math.round(hours / 24)}d`;
}

function branchMessages(branch: SessionEntry[]) {
	let start = 0;
	const messages: Parameters<typeof convertToLlm>[0] = [];
	for (let i = branch.length - 1; i >= 0; i--) {
		const entry = branch[i];
		if (entry.type === "compaction") {
			messages.push({
				role: "compactionSummary" as const,
				summary: entry.summary,
				tokensBefore: entry.tokensBefore,
				timestamp: new Date(entry.timestamp).getTime(),
			});
			const kept = branch.findIndex((e) => e.id === entry.firstKeptEntryId);
			start = kept >= 0 && kept < i ? kept : i + 1;
			break;
		}
	}
	for (const entry of branch.slice(start)) {
		if (entry.type === "message") messages.push(entry.message);
	}
	return messages;
}

export default function (pi: ExtensionAPI) {
	let ctx: ExtensionContext | undefined;
	let storeDir = "";
	let record: SessionRecord | undefined;
	let pulse: Pulse | undefined;
	let workspacePulse: Pulse | undefined;
	let others: SessionRecord[] = [];
	let lastSummarizedCount = 0;
	let lastSummaryAt = 0;
	let runStartedAt = 0;
	let summarizing: Promise<void> | undefined;
	let rerun: { persist: boolean } | undefined;
	let workspaceFingerprint = "";
	let workspaceDigestAt = 0;
	let digesting = false;
	let panelOpen = false;
	let timer: ReturnType<typeof setInterval> | undefined;
	// The pi API throws once the session shuts down, and summaries can land after that.
	let active = false;
	let tmuxTitle = "";

	// The title is a pane option, and the window's automatic name shows the active pane's title,
	// so several agents split across one window each get their own name. An empty title unsets it.
	function setTmuxTitle(title: string, sync = false) {
		if (!TMUX_PANE || title === tmuxTitle) return;
		tmuxTitle = title;
		const args = title
			? [
					...["set-option", "-p", "-t", TMUX_PANE, TMUX_TITLE_OPTION, title, ";"],
					...["set-option", "-w", "-t", TMUX_PANE, "automatic-rename-format", TMUX_NAME_FORMAT, ";"],
					...["set-option", "-w", "-t", TMUX_PANE, "automatic-rename", "on"],
				]
			: ["set-option", "-p", "-u", "-t", TMUX_PANE, TMUX_TITLE_OPTION];
		if (sync) {
			// Only used at shutdown, when the pane or tmux server may already be gone.
			try {
				execFileSync("tmux", args, { stdio: "ignore", timeout: 2000 });
			} catch {}
			return;
		}
		execFile("tmux", args, { timeout: 2000 }, (error) => error && logError("tmux", error));
	}

	function register() {
		pi.events.emit("powerbar:register-segment", { id: "session-name", label: "Session Name" });
		pi.events.emit("powerbar:register-segment", { id: "session-summary", label: "Session Summary" });
		pi.events.emit("powerbar:register-segment", { id: "workspace-context", label: "Workspace Context" });
	}

	// The Cursor provider shares one `--resume` chat per pi process and drops the system prompt
	// when resuming, so a side call through it lands in the main conversation's Cursor chat.
	const isolated = (model: ExtensionContext["model"]) => model && model.api !== "cursor-cli";

	function resolveModel(c: ExtensionContext) {
		const [provider, ...rest] = MODEL_SPEC.split("/");
		const preferred = c.modelRegistry.find(provider, rest.join("/"));
		if (isolated(preferred) && c.modelRegistry.hasConfiguredAuth(preferred!)) return preferred;
		return isolated(c.model) ? c.model : undefined;
	}

	async function ask(c: ExtensionContext, systemPrompt: string, input: string): Promise<Pulse | undefined> {
		const model = resolveModel(c);
		if (!model) {
			logError("model", `${MODEL_SPEC} is unavailable and the session model is a Cursor CLI model; set PI_PULSE_MODEL`);
			return undefined;
		}
		const text = `${input}\n\n---\n${systemPrompt}\nReply with only the lines in exactly that output format.`;
		const response = await c.modelRegistry.complete(
			model,
			{ systemPrompt, messages: [{ role: "user", content: [{ type: "text", text }], timestamp: Date.now() }] },
			{ cacheRetention: "none", sessionId: randomUUID() },
		);
		const output = response.content
			.filter((part): part is { type: "text"; text: string } => part.type === "text")
			.map((part) => part.text)
			.join("\n");
		const parsed = parsePulse(output);
		if (!parsed) logError(`unparseable ${model.provider}/${model.id} response`, response.errorMessage ?? output.slice(0, 500));
		return parsed;
	}

	function publish() {
		if (!active || !record || !storeDir) return;
		Object.assign(record, pulse ?? {}, { name: pi.getSessionName(), updatedAt: Date.now() });
		try {
			mkdirSync(storeDir, { recursive: true });
			const path = join(storeDir, `${record.sessionId}.json`);
			writeFileSync(`${path}.tmp`, JSON.stringify(record, null, "\t"));
			renameSync(`${path}.tmp`, path);
		} catch {}
	}

	function readOthers(): SessionRecord[] {
		if (!storeDir || !record) return [];
		let files: string[] = [];
		try {
			files = readdirSync(storeDir).filter((file) => file.endsWith(".json"));
		} catch {
			return [];
		}
		const now = Date.now();
		const result: SessionRecord[] = [];
		for (const file of files) {
			try {
				const other = JSON.parse(readFileSync(join(storeDir, file), "utf8")) as SessionRecord;
				if (other.sessionId === record.sessionId || now - other.updatedAt > RECENT_MS) continue;
				if (other.state !== "ended" && !pidAlive(other.pid)) other.state = "ended";
				result.push(other);
			} catch {}
		}
		return result.sort((a, b) => b.updatedAt - a.updatedAt);
	}

	function render() {
		if (!active) return;
		const working = record?.state === "working";
		// An empty update removes the segment until the session has a name.
		pi.events.emit("powerbar:update", { id: "session-name", icon: "✎", text: pi.getSessionName() ?? "", color: "accent" });
		if (pulse) {
			pi.events.emit("powerbar:update", {
				id: "session-summary",
				icon: working ? "▶" : "◆",
				text: pulse.headline,
				color: working ? "accent" : "text",
			});
			setTmuxTitle(clip(`${working ? "▶" : "◆"} ${pi.getSessionName() ?? pulse.headline}`, TMUX_WIDTH));
		} else {
			pi.events.emit("powerbar:update", {
				id: "session-summary",
				icon: working ? "▶" : "◆",
				text: working ? "summarizing after this run…" : "new session",
				color: "muted",
			});
		}

		const counts = { working: 0, idle: 0, ended: 0 };
		for (const other of others) counts[other.state]++;
		const tally = [
			counts.working && `${counts.working}▶`,
			counts.idle && `${counts.idle}◆`,
			counts.ended && `${counts.ended}✓`,
		]
			.filter(Boolean)
			.join(" ");
		const workspaceText = others.length
			? `${tally} ${workspacePulse?.headline ?? others[0].headline ?? ""}`.trim()
			: "no other sessions";
		pi.events.emit("powerbar:update", {
			id: "workspace-context",
			icon: "⌂",
			text: workspaceText,
			color: others.length ? "text" : "muted",
		});

		if (ctx?.hasUI) ctx.ui.setWidget("session-pulse", panelOpen ? panelFactory : undefined);
	}

	const panelFactory = (_tui: unknown, theme: ExtensionContext["ui"]["theme"]) => ({
		invalidate() {},
		render(width: number): string[] {
			const fit = (line: string) => truncateToWidth(line, width, "…");
			const lines: string[] = [];
			lines.push(fit(theme.fg("accent", theme.bold(`◆ This session: ${pulse?.headline ?? "no summary yet"}`))));
			for (const line of (pulse?.summary ?? "").split("\n").filter(Boolean)) lines.push(fit(`  ${line}`));
			lines.push(
				fit(theme.fg("accent", theme.bold(`⌂ Workspace: ${workspacePulse?.headline ?? `${others.length} other sessions`}`))),
			);
			for (const line of (workspacePulse?.summary ?? "").split("\n").filter(Boolean)) lines.push(fit(`  ${line}`));
			const now = Date.now();
			for (const other of others.slice(0, 8)) {
				const icon = other.state === "working" ? "▶" : other.state === "idle" ? "◆" : "✓";
				const label = other.name ? `${other.name}: ` : "";
				lines.push(fit(theme.fg("dim", `  ${icon} ${age(now - other.updatedAt).padStart(4)}  ${label}${other.headline || "(no summary)"}`)));
			}
			return lines;
		},
	});

	async function summarizeSession(persist: boolean): Promise<void> {
		if (summarizing) {
			rerun = { persist: persist || Boolean(rerun?.persist) };
			return summarizing;
		}
		const c = ctx;
		if (!c) return;
		const branch = c.sessionManager.getBranch();
		if (branch.length === lastSummarizedCount) return;
		const messages = branchMessages(branch);
		if (messages.length === 0) return;

		summarizing = (async () => {
			try {
				let transcript = serializeConversation(convertToLlm(messages));
				if (transcript.length > MAX_TRANSCRIPT_CHARS) {
					transcript = `[…earlier conversation truncated…]\n${transcript.slice(-MAX_TRANSCRIPT_CHARS)}`;
				}
				const previous = pulse
					? `${pulse.name ? `NAME: ${pulse.name}\n` : ""}HEADLINE: ${pulse.headline}\n${pulse.summary}`
					: "(none)";
				const next = await ask(
					c,
					SESSION_PROMPT,
					`<previous_summary>\n${previous}\n</previous_summary>\n\n<transcript>\n${transcript}\n</transcript>`,
				);
				if (!next || !active) return;
				const previousName = pulse?.name;
				next.name ??= previousName;
				// A name that differs from the last generated one was set by the user with /name.
				const current = pi.getSessionName();
				if (next.name && next.name !== current && (!current || current === previousName)) {
					pi.setSessionName(next.name);
				}
				pulse = next;
				lastSummarizedCount = branch.length;
				lastSummaryAt = Date.now();
				if (persist) pi.appendEntry<Pulse>(ENTRY_TYPE, next);
				publish();
				render();
			} catch (error) {
				logError("session summary", error);
			} finally {
				summarizing = undefined;
				if (rerun && active) {
					const queued = rerun;
					rerun = undefined;
					void summarizeSession(queued.persist);
				}
			}
		})();
		return summarizing;
	}

	async function refreshWorkspace(force = false) {
		if (!active) return;
		others = readOthers();
		render();
		const c = ctx;
		if (!c || digesting || others.length === 0) {
			if (others.length === 0) workspacePulse = undefined;
			return;
		}
		const fingerprint = others.map((o) => `${o.sessionId}:${o.state}:${o.headline}`).join("|");
		if (!force && (fingerprint === workspaceFingerprint || Date.now() - workspaceDigestAt < WORKSPACE_DIGEST_MIN_MS)) {
			return;
		}
		digesting = true;
		try {
			const now = Date.now();
			const sessions = [record, ...others]
				.filter((s): s is SessionRecord => Boolean(s?.headline))
				.map(
					(s) =>
						`### ${s.sessionId === record?.sessionId ? "this session" : s.name || s.sessionId.slice(-8)} ` +
						`(${s.state}, updated ${age(now - s.updatedAt)} ago, cwd ${s.cwd})\n` +
						`HEADLINE: ${s.headline}\n${s.summary}`,
				)
				.join("\n\n");
			if (!sessions) return;
			const next = await ask(c, WORKSPACE_PROMPT, `<sessions>\n${sessions}\n</sessions>`);
			if (next && active) {
				workspacePulse = next;
				workspaceFingerprint = fingerprint;
				workspaceDigestAt = Date.now();
				render();
			}
		} catch (error) {
			logError("workspace digest", error);
		} finally {
			digesting = false;
		}
	}

	register();

	pi.on("session_start", async (_event, c) => {
		// Print/JSON runs and subagents would spend a model call and clutter the workspace view.
		if (c.mode !== "tui" && !process.env.PI_PULSE_ALL_MODES) return;
		active = true;
		ctx = c;
		register();
		storeDir = join(STORE_ROOT, workspaceKey(c.cwd));
		pulse = undefined;
		workspacePulse = undefined;
		workspaceFingerprint = "";
		const branch = c.sessionManager.getBranch();
		for (let i = branch.length - 1; i >= 0; i--) {
			const entry = branch[i];
			if (entry.type === "custom" && entry.customType === ENTRY_TYPE) {
				pulse = entry.data as Pulse;
				lastSummarizedCount = i + 1;
				break;
			}
		}
		record = {
			sessionId: c.sessionManager.getSessionId(),
			sessionFile: c.sessionManager.getSessionFile(),
			cwd: c.cwd,
			pid: process.pid,
			state: "idle",
			updatedAt: Date.now(),
			headline: pulse?.headline ?? "",
			summary: pulse?.summary ?? "",
		};
		publish();
		if (timer) clearInterval(timer);
		timer = setInterval(() => void refreshWorkspace(), WORKSPACE_POLL_MS);
		await refreshWorkspace(true);
	});

	pi.on("agent_start", async (_event, c) => {
		if (!active) return;
		ctx = c;
		if (record) record.state = "working";
		runStartedAt = Date.now();
		publish();
		render();
	});

	pi.on("turn_end", async (_event, c) => {
		if (!active) return;
		ctx = c;
		if (Date.now() - Math.max(lastSummaryAt, runStartedAt) > MID_RUN_REFRESH_MS) void summarizeSession(false);
	});

	pi.on("agent_settled", async (_event, c) => {
		if (!active) return;
		ctx = c;
		if (record) record.state = "idle";
		publish();
		render();
		void summarizeSession(true)
			.then(() => refreshWorkspace())
			.catch(() => {});
	});

	pi.on("session_info_changed", async () => {
		publish();
		render();
	});

	pi.on("session_shutdown", async () => {
		if (timer) clearInterval(timer);
		timer = undefined;
		if (record) record.state = "ended";
		publish();
		setTmuxTitle("", true);
		active = false;
		ctx = undefined;
	});

	pi.registerCommand("pulse", {
		description: "Toggle the session/workspace summary panel (/pulse refresh to regenerate)",
		handler: async (args, c) => {
			if (!active) {
				c.ui.notify("session-pulse only runs in interactive sessions", "warning");
				return;
			}
			ctx = c;
			if (args.trim() === "refresh") {
				lastSummarizedCount = 0;
				c.ui.notify("Refreshing summaries…", "info");
				await summarizeSession(true);
				await refreshWorkspace(true);
				return;
			}
			panelOpen = !panelOpen;
			render();
		},
	});
}
