- block:
  - name: Install Mosh for MacOS
    become: no
    homebrew:
        name: mosh
        state: latest

  - name: Insert/Update .bashrc to prepand /usr/local/bin to system path and prefer homebrew installs
    become: no
    blockinfile:
      path: ~/.bashrc
      create: yes
      insertafter: EOF
      mode: 0664
      block: |
        export PATH=/usr/local/bin:$PATH

  - name: Source bashrc
    include_role:
      name: dotfiles
      tasks_from: source_bashrc
