- block:
  - name: Copy relevant dotfiles
    become: no
    copy:
      src: "{{ item }}"
      dest: "~/"
      mode: 0664
    loop:
      - .carden_bashrc
      - .ctags
    tags: dotfiles

  - name: Insert/Update .bashrc to also source the .carden_bashrc
    become: no
    blockinfile:
      path: ~/.bashrc
      create: yes
      insertafter: EOF
      mode: 0664
      block: |
        if [ -f ~/.carden_bashrc ]; then . ~/.carden_bashrc; fi

  - name: Source bashrc
    include_role:
      name: dotfiles
      tasks_from: source_bashrc

  - name: Refresh tmux conf
    include_role:
      name: tmux
      tasks_from: tmux_conf

  - name: Refresh vimrc
    include_role:
      name: vim
      tasks_from: vimrc

  - name: Set gitconfig
    include_role:
      name: git
      tasks_from: dotfiles
