- block:
  - name: Source bashrc
    become: no
    shell: ". ~/.bashrc"
    ignore_errors: True
    register: src_result

  - name: Abort if failure occured when not cuise
    become: no
    fail:
      msg: >-
        Failure occured that is not acceptable.
    when: src_result.failed and not cruise
