- block:
  - include: "{{ ansible_distribution }}.yml"

  - name: Install python packages
    pip:
      executable: pip3
      name: termcolor
      state: latest
      extra_args: --user
    tags: [python, gitflow]
