- block:
  - include_tasks: "{{ ansible_distribution }}.yml"

  - name: Install termcolor for gitflow
    pip:
      virtualenv: "{{ venv_dir }}"
      name: termcolor
      state: latest
    tags: [python, gitflow]

  - name: Install general python packages.
    pip:
      virtualenv: "{{ venv_dir }}"
      name:
        - autopep8
        - yapf
        - black
        - ipdb
        - ipython
        - isort
      state: latest
    tags: [python]

  - name: Copy ipython config.
    become: no
    copy:
      src: "{{ item }}"
      dest: "~/.ipython/profile_default/"
      mode: 0664
    loop:
      - ipython_config.py
    tags: [python]

  - name: Manage virtual environments
    pip:
      virtualenv: "{{ venv_dir }}"
      name: virtualenvwrapper
      state: latest
    tags: [python]
