- block:
  - include: "{{ ansible_distribution }}.yml"

  - name: Install termcolor for gitflow
    pip:
      executable: pip3
      name: termcolor
      state: latest
      extra_args: --user
    tags: [python, gitflow]

  - name: Install general python packages.
    pip:
      executable: pip3
      name:
        - autopep8
        - yapf
        - ipdb
        - ipython
      state: latest
      extra_args: --user
    tags: [python]

  - name: Copy ipython config.
    become: no
    copy:
      src: "{{ item }}"
      dest: "~/.ipython/profile_default/"
      mode: 0664
    loop:
      - ipython_config.py
    tags: [python]

  - name: Manage virtual environments
    pip:
      executable: pip3
      name: virtualenvwrapper
      state: latest
      extra_args: --user
    tags: [python]
