- block:
  - name: Copy relevant dotfiles
    become: no
    copy:
      src: "{{ item }}"
      dest: "~/"
      mode: 0664
    loop:
      - .gitconfig
      - .gitignore

  - name: Insert github enterprise host to git config for hubcli.
    become: no
    when: cruise
    git_config:
        name: hub.host
        scope: global
        value: github.robot.car

  - name: Check if github token file already exists.
    become: no
    stat:
      path: "~/.github_token"
    register: github_token_state
    when: cruise

  - name: Create place to store github token for hub cli
    become: no
    when: cruise and not github_token_state.stat.exists
    blockinfile:
      path: ~/.github_token
      create: yes
      insertafter: EOF
      mode: 0664
      marker_begin: "Generate personal access token on github and insert below:"
      block: |
        export GITHUB_TOKEN=

  - name: Source github token file in bashrc
    become: no
    when: cruise
    blockinfile:
      path: ~/.bashrc
      create: yes
      insertafter: EOF
      mode: 0664
      marker_begin: "Source hubcli token"
      block: |
        . ~/.github_token

  - name: Insert github enterprise host to git config for hubcli.
    become: no
    when: zoox
    git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
    with_items:
        - {name: "hub.host", value: "git.zooxlabs.com"}
        - {name: "hub.protocal", value: "https"}
