- block:
  # Install tmux according to platform.
  - include: "{{ ansible_distribution }}.yml"

  - name: Set up tmux plugin manager
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: "{{ home_dir }}/.tmux/plugins/tpm"

  # Setup .tmux.conf
  - include: "tmux_conf.yml"

  - name: Install tmux plugins
    command:
      cmd: "{{ home_dir }}/.tmux/plugins/tpm/bin/install_plugins"
