- block:
  - name: Check if YouCompleteMe directory exists
    become: no
    stat:
      path: "{{ ycm_dir }}"
    register: ycm_dir_state

  - name: Abort if ycm_dir does not exist.
    become: no
    fail:
      msg: >-
        YouCompleteMe not installed with vundle. Please install vim with the vim
        playbook.
    when: not (ycm_dir_state.stat.exists or ycm_dir_state.stat.isdir)

  # Install dependencies according to platform.
  - include_tasks: "{{ ansible_distribution }}.yml"
