- block:
  - name: Install YouCompleteMe dependencies
    become: yes
    apt:
      pkg:
        - build-essential
        - g++-8
        - gcc-8
      state: latest

  - name: Install YouCompleteMe
    become: no
    environment:
      CC: gcc-8
      CXX: g++-8
    command:
      chdir: "{{ ycm_dir }}"
      cmd: >-
        python3.7 install.py --clangd-completer --cmake-path={{ cmake_install_dir}}bin/cmake
