- block:
  - name: Install python3.6
    apt:
      name: python3.6
      state: latest
    tags: python

  - name: Install pip for python3
    apt:
      name: python3-pip
      state: latest
    tags: python

  - name: Install python packages
    pip:
      executable: pip3
      name: GitPython
      state: latest
    tags: [python, gitflow]

  - name: Remove previous vim installation
    apt:
      name: vim
      state: absent
    tags: vim

  - name: Install vim from source
    script: install_vim.sh
    tags: vim

  - name: install tmux
    apt:
      name: tmux
      state: latest
    tags: tmux

  - name: Copy relevant dotfiles
    copy:
      src: "{{ item }}"
      dest: "~/{{ item }}"
      mode: 0664
    loop:
      - .bashrc
      - .ctags
      - .gitconfig
      - .tmux.conf
      - .vimrc
      - .vim
    tags: dotfiles

  - name: Set up Vundle and Tmux
    script: dotfile_setup.sh
    tags: dotfiles

  - name: Make local directory for commands.
    file:
      path: ~/.local/bin/
      state: directory
    tags: [gitflow]

  - name: Install gitflow
    copy:
      src: gitflow.py
      dest: ~/.local/bin/gitflow
    tags: gitflow
