- name: Install vim for MacOS
  become: no
  homebrew:
      name: vim
      state: latest

- name: Install yarn for MacOS, needed for CoC.nvim
  become: no
  homebrew:
      name: yarn
      state: latest
