- name: Install vim for MacOS
  become: no
  homebrew:
      name: vim
      state: latest

- name: Install yarn for MacOS, needed for CoC.nvim
  become: no
  homebrew:
      name: yarn
      state: latest

- name: Install Node.js and NPM for CoC.nvim on macOS
  homebrew:
    name: node
    state: present
