- block:
  # Install vim in a platform independent way.
  - include: "{{ ansible_distribution }}.yml"

  - name: Set up vundle plugin manager
    become: no
    git:
      repo: git@github.com:VundleVim/Vundle.vim.git
      dest: "{{ home_dir }}/.vim/bundle/Vundle.vim"

  # Configure vimrc
  - include: "vimrc.yml"
